default:
  - src: '/sounds/boop.mp3'
    type: 'audio/mpeg'
  - src: '/sounds/boop.ogg'
    type: 'audio/ogg'
laser:
  - src: '/sounds/laser.mp3'
    type: 'audio/mpeg'
  - src: '/sounds/laser.ogg'
    type: 'audio/ogg'
