---
de:
  simple_form:
    glitch_only: glitch-soc
    hints:
      defaults:
        fields: Du kannst bis zu %{count} Elemente auf deinem Profil anzeigen lassen, die als Tabelle dargestellt werden
        setting_default_content_type_html: Beim Schreiben von Toots annehmen, dass sie in rohem HTML geschrieben sind, sofern nicht anders angegeben
        setting_default_content_type_markdown: Beim Schreiben von Toots annehmen, dass sie in Markdown für Rich-Text-Formatierung geschrieben sind, sofern nicht anders angegeben
        setting_default_content_type_plain: Beim Schreiben von Toots annehmen, dass sie in Klartext ohne spezielle Formatierung geschrieben sind, sofern nicht anders angegeben (standardmäßiges Mastodon-Verhalten)
        setting_default_language: Die Sprache deiner Toots kann automatisch erkannt werden, aber sie ist nicht immer korrekt
        setting_hide_followers_count: Verberge deine Follower-Anzahl vor allen, einschließlich dir. Manche Anwendungen könnten eine negative Follower-Anzahl anzeigen.
        setting_norss: Mastodon erstellt automatisch ein RSS feed aller öffentlichen Toots.
        setting_skin: Verändert die ausgewählte Mastodon-Variante
      form_admin_settings:
        publish_button_text: Überschreibt den Text des Toot-buttons.
        search_preview: Ausgeloggte Benutzer*innen können die Suchfunktion nutzen.
        trends_as_landing_page: Zeige ausgeloggten Nutzer*innen Trends anstatt der Instanzbeschreibung. Erfordert aktivierte Trends.
      invite:
        comment: Optional. Du kannst angeben für wen diese Einladung ist, oder den Grund der Erstellung.
    labels:
      defaults:
        setting_default_content_type: Standardformat für Toots
        setting_default_content_type_html: HTML
        setting_default_content_type_markdown: Markdown
        setting_default_content_type_plain: Unformatierter Text
        setting_favourite_modal: Bestätigungsdialog vor dem Favorisieren anzeigen (gilt nur für Glitch-Variante)
        setting_hide_followers_count: Anzahl der Follower verbergen
        setting_norss: Deaktiviere RSS Feed von deinen Toots
        setting_notification_sound: Benachrichtigungston
        setting_skin: Skin
        setting_system_emoji_font: Systemschriftart für Emojis verwenden (nur für Glitch-Variante)
        setting_visible_reactions: Anzahl der sichtbaren Emoji-Reaktionen
      form_admin_settings:
        publish_button_text: Toot-button Text
        search_preview: Erlaube nicht-authentifizierten Zugriff auf die Suchfunktion
        trends_as_landing_page: Nutze Trends als Startseite
      notification_emails:
        trending_link: Neuer angesagter Link muss überprüft werden
        trending_status: Neuer angesagter Post muss überprüft werden
        trending_tag: Neuer angesagter Tag muss überprüft werden
